[package]
name = "deltachat-echo-bot"
version = "0.1.0"
authors = ["DeltaChatBot Contributers<https://github.com/deltachat-bot>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltachat = { git = "https://github.com/deltachat/deltachat-core-rust", tag="1.75.0"}
ctrlc = { version = "3.1.7", features = ["termination"] }
async-std = { version = "1.7.0", features = ["attributes"] }
futures-lite = "1.11.2"
anyhow = "1.0.54"


# this is required until https://github.com/deltachat/deltachat-core-rust/issues/3080 is solved
[patch.crates-io]
rusqlite = {git="https://github.com/rusqlite/rusqlite", rev = "ddb7141c6dee4b8956af85b2e4a01a28e5fdbacc" }
