[package]
name = "deltachat-echo-bot"
version = "0.1.0"
authors = ["DeltaChatBot Contributers<https://github.com/deltachat-bot>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltachat = { git = "https://github.com/deltachat/deltachat-core-rust", tag="1.48.0"}
ctrlc = { version = "3.1.7", features = ["termination"] }
async-std = { version = "1.7.0", features = ["attributes"] }
futures-lite = "1.11.2"
